/**
 * 
 */
/**
 * @author diegoceb
 *
 */
module Proyecto1 {
}

/*INDICE DE TEMAS POR PAQUETE
	 * CADENA: CONTAR.CARACTRERS - CONTAR.VOCALES - CONTAR.PALABRAS - CONTAR.CONSONANTES
	 * COMPLEJOS: CONSTRUCTOR Y SOBRECARGA - GETTERS AND SETTERS
	 * VIRUS: RANDOM - SCANNER - TO.STRING
	 * PUNTO: TO.STRING - METODOS
	 * MONEDA: FUERTE USO DE RANDOM Y SCANNER
	 * VENTAS: ARRAYS
	 * FECHAS: INGRESO, SALIDA Y TRABAJOS CON FECHAS
	 * TECNICO: ARRAY LIST
	 * EQUIPO: ARRAYLIST
	 * CLINICA CLASE 8: HERENCIA
 	 * EMPRESA CLASE 8: HERENCIA
 	 * EMPRESA.PT2 CLASE 9: HERENCIA Y POLIMORFISMO
 * 
 *PENDIENTES:
 	* PRECIPITACIONES CLASE 6: ARRAYS
 	* EXPRIMIDORA CLASE 9: HERENCIA Y POLIMORFISMO
 */
